sudo: false
language: java

jdk:
  - oraclejdk8

script:
  - make build deploy

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/postman/node_modules
    - $HOME/aws-lambda/node_modules

after_success:
    - ./gradlew jacocoRootReport coveralls